services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      LOG_LEVEL: trace
      DB_HOST: database
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: subscriberest_dev
      DB_PORT: 5432
      DB_SSLMODE: disable
      PORT: 8080
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subscriberest_dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always
    ports:
      - "5050:80"

volumes:
  postgres_data:
